source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target :Brewer do
    pod 'Swinject', '~> 2.1.1 '
    pod 'SwinjectStoryboard', '~> 1.1.2'

    pod 'RxSwift', '~> 4.0.0'
    pod 'RxCocoa', '~> 4.0.0'

    pod 'ObjectMapper'
    pod 'XCGLogger', '~> 4.0.0'
    pod 'FormatterKit'
    pod 'DZNEmptyDataSet'

    pod 'Google/Analytics'
    pod 'Fabric'
    pod 'Crashlytics'
    
    target :BrewerTests do
        
        pod 'Quick'
        pod 'Nimble', '~> 7.0.0'
        pod 'RxTest', '~> 4.0.0'
        pod 'RxBlocking', '~> 4.0.0'
    end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
