disabled_rules: # rule identifiers to exclude from running
  - comma
  - control_statement
  - trailing_whitespace
  - force_cast
  - statement_position
  - closure_parameter_position
  - vertical_parameter_alignment
  - identifier_name
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Brewer
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 158
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 400
  error: 600
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 45
    error: 55
variable_name:
  min_length: # only min_length
    warning: 3 # only error
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
